---
project_dir: ~/Projet
downloads_dir: ~/Downloads

downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_osx: yes

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Projet/tmp/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - automake
  - bash-completion
  - chromedriver
  - doxygen
  - gettext
  - gifsicle
  - git
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - yarn
  - nvm
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - curl
  - consul
  - docker-compose
  - docker-machine-driver-xhyve
  - docker-machine-nfs
  - docker-machine
  - heroku
  - htop
  - mas
  - ncdu
  - nmap
  - packer
  - scw
  - terraform
  - terminal-notifier
  - wget
  - xhyve
  - zsh
  - zsh-completions
  - tree
  - dockutil
  - watch


homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/php

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-chrome
  - sequel-pro
  - alfred
  - iterm2
  - spotify
#  - virtualbox
  - dash
  - cleanmymac
  - etcher
  - yakyak
#  - docker-edge
  - vlc
  - istat-menus
  - sublime-text
  - dropbox

# See `geerlingguy.mas` role documentation for usage instructions.
mas_signin_dialog: yes
mas_installed_apps:
  - { id: 409183694, name: "Keynote" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409201541, name: "Pages" }

mas_upgrade_all_apps: yes

osx_script: "~/.osx --no-restart"

dockitems_disabled:
  - Launchpad
  - Siri
  - Mail
  - Safari
  - Contacts
  - Notes
  - Rappels
  - Maps
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - Terminal
  - Plans
  - Pages
  - Numbers
  - Keynote

dockitems_enabled:
  - name: Calendrier
    path: "/Applications/Calendar.app"
    pos: 1
  - name: Photos
    path: "/Applications/Photos.app"
    pos: 2
  - name: Messages
    path: "/Applications/Messages.app"
    pos: 3
  - name: Préférences Système
    path: "/Applications/System Preferences.app"
    pos: 4
  - name: iTerm
    path: "/Applications/iTerm.app"
    pos: 5
  - name: YakYak
    path: "/Applications/YakYak.app"
    pos: 6
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 7
  - name: Spotify
    path: "/Applications/Spotify.app"
    pos: 8
  - name: Dash
    path: "/Applications/Dash.app"
    pos: 14
  - name: Sublime Text
    path: "/Applications/Sublime Text.app"
    pos: 14
